#!/bin/bash

set -e

# Ability to pass cross compilation flags
# "--host=i686-w64-mingw32 --build=x86_64-pc-linux-gnu" for Windows
CROSS_COMPILE_FLAGS="$1"
GIT_COMMIT="4c908dde58ef780eeefcc9df4db3063ca62ea862" # version 2.1.11

here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
. "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)

which git || fail "Git is required to proceed"

pkgname="libevent"
info "Building $pkgname..."

pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
git checkout $GIT_COMMIT || fail "Could not check out $pkgname $GIT_COMMIT"
git clean -dfxq
./autogen.sh || fail "Could not configure $pkgname"
./configure \
    $CROSS_COMPILE_FLAGS \
    --prefix="$here/$pkgname/dist" \
    --disable-shared \
    --enable-static \
    --with-pic \
    --disable-samples \
    --disable-libevent-regress \
    CPPFLAGS=-I"$here"/openssl/dist \
    LDFLAGS=-L"$here"/openssl/dist || fail "Could not configure $pkgname"
make -j$WORKER_COUNT || fail "Could not build $pkgname"
make install || fail "Could not install $pkgname"
git checkout master  # Undo the previous explicit checkout to this hash
git clean -dfxq
popd
