#!/bin/bash

set -e

# Ability to pass cross compilation flags
# "--host=i686-w64-mingw32 --build=x86_64-pc-linux-gnu" for Windows
CROSS_COMPILE_FLAGS="${CROSS_COMPILE_FLAGS:-$1}"
GIT_COMMIT="1d51925e6cc9151f4a73781989f21fcd7b57ef32" # version 0.23

here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
. "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)

which git || fail "Git is required to proceed"

pkgname="zbar"
info "Building $pkgname..."

pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
git checkout $GIT_COMMIT || fail "Could not check out $pkgname $GIT_COMMIT"
git clean -dfxq
autoreconf -vfi || fail "Could not run autoreconf for $pkgname. Please make sure you have automake and libtool installed, and try again."
./configure \
    $CROSS_COMPILE_FLAGS \
    --prefix="$here/$pkgname/dist" \
    --with-x=no \
    --enable-pthread=no \
    --enable-doc=no \
    --enable-video=no \
    --with-jpeg=no \
    --with-python=no \
    --with-gtk=no \
    --with-qt=no \
    --with-java=no \
    --with-imagemagick=no \
    --with-dbus=no \
    --enable-codes=qrcode \
    --disable-static \
    --enable-shared || fail "Could not configure $pkgname. Please make sure you have a C compiler installed and try again."
make -j$WORKER_COUNT || fail "Could not build $pkgname"
make install || fail "Could not install $pkgname"
. "$here/$pkgname/dist/lib/libzbar.la"
cp -fpv "$here/$pkgname/dist/lib/$dlname" "$here/../lib" || fail "Could not copy the $pkgname binary to its destination"
info "$dlname has been placed in the 'lib' folder."
git checkout master  # Undo the previous explicit checkout to this hash
git clean -dfxq
popd
