#!/bin/bash

set -e

here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
. "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)

pkgname="zlib"
info "Building $pkgname..."

pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
if [ "$BUILD_TYPE" = "wine" ] ; then
    PREFIX="$here/$pkgname/dist"
    BINARY_PATH="$PREFIX/bin"
    INCLUDE_PATH="$PREFIX/include"
    LIBRARY_PATH="$PREFIX/lib"
    make -j$WORKER_COUNT -fwin32/Makefile.gcc
    make install -fwin32/Makefile.gcc
else
    if ! [ -r config.status ] ; then
        ./configure \
            $AUTOCONF_FLAGS \
            --prefix="$here/$pkgname/dist" || fail "Could not configure $pkgname"
    fi
    make -j$WORKER_COUNT || fail "Could not build $pkgname"
    make install || fail "Could not install $pkgname"
fi
popd
