FROM debian:10.4@sha256:68f4e2259032a4e6f5035804e64438b52af8dd5889528b305b9059183ea4cd2a

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

# The sed line switches the mirror to snapshot.debian.org, which will make the container build reproducible
RUN sed -i -e '/^deb/d' -e 's/^# //' /etc/apt/sources.list && \
    apt-get update -q && \
    apt-get install -qy \
        wget=1.20.1-1.1 \
        make=4.2.1-1.2 \
        autotools-dev=20180224.1 \
        autoconf=2.69-11 \
        libtool=2.4.6-9 \
        xz-utils=5.2.4-1 \
        libffi-dev=3.2.1-9 \
        libncurses5-dev=6.1+20181013-2+deb10u2 \
        libsqlite3-dev=3.27.2-3 \
        libusb-1.0-0-dev=2:1.0.22-2 \
        libudev-dev=241-7~deb10u4 \
        gettext=0.19.8.1-9 \
        pkg-config=0.29-6 \
        libdbus-1-3=1.12.16-1 \
        libpcsclite-dev=1.8.24-1 \
        swig=3.0.12-2 \
        libxkbcommon-x11-0=0.8.2-1 \
        git=1:2.20.1-2+deb10u3 \
        zlib1g-dev=1:1.2.11.dfsg-1 \
        libfreetype6=2.9.1-3+deb10u1 \
        libfontconfig1=2.13.1-2 \
        libssl-dev=1.1.1d-0+deb10u3 \
        libssl1.1=1.1.1d-0+deb10u3 \
        && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean
