FROM electroncash-appimage-builder-img-ub1604

# Hack to switch from xenial to bionic. Normally you shouldn't mix these but
# if you do, you need to make sure that what you install doesn't cause
# conflicts. Best to install only packages with very few dependencies from
# the newer version.
RUN sed -i -e 's/xenial/bionic/' /etc/apt/sources.list

# The Ubuntu 16.04 freetype / fontconfig does not seem to properly support
# color emojis. To support those we get a newer freetype / fontconfig combo
# from the Ubuntu 18.04 repo.
# We also install OpenSSL 1.1 to have that be available accross all the
# platforms we support.
RUN apt-get update -q && \
    apt-get install -qy \
        zlib1g-dev=1:1.2.11.dfsg-0ubuntu2 \
        libfreetype6=2.8.1-2ubuntu2 \
        libfontconfig1=2.12.6-0ubuntu2 \
        libssl-dev=1.1.0g-2ubuntu4.3 \
        libssl1.1=1.1.0g-2ubuntu4.3 \
        && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean
